
CREATE TABLE WIKJ.T_WIKJ_HAB_PRUEBAFINAL (
    id NUMBER(5) NOT NULL PRIMARY KEY,
    nuip NUMBER(10),
    full_name VARCHAR2(50),
    phone VARCHAR2(15),
    address VARCHAR2(30)
);

SELECT ID, NUIP, FULL_NAME, PHONE, ADDRESS
FROM WIKJ.T_WIKJ_HAB_PRUEBAFINAL;

INSERT INTO WIKJ.T_WIKJ_HAB_PRUEBAFINAL
(ID, NUIP, FULL_NAME, PHONE, ADDRESS)
VALUES(0, 0, '', '', '');

SE ORGANIZAN QUERYS


SELECT id, nuip, full_name, phone, address FROM WIKJ.T_WIKJ_HAB_PRUEBAFINAL WHERE id = :id;

INSERT INTO WIKJ.T_WIKJ_HAB_PRUEBAFINAL (id, nuip, full_name, phone, address) VALUES(:id, :nuip, :full_name, :phone, :address);

